name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check repository files present
        run: |
          test -f src/asa_audit.ps1
          test -f README.md
          test -f LICENSE
  pester:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.0.0
      - name: Run tests
        shell: pwsh
        run: Invoke-Pester -Path tests -CI
